name: "\U0001F41E Bug report"
description: for reproducible bugs in vite-plugin-svelte only.
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for participating in vite-plugin-svelte! Please make sure that you are reporting a bug that is caused by vite-plugin-svelte and check for existing reports before creating a new one.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction URL
      description: A link to a repository or a fork of https://vite.new/svelte, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.
      placeholder: https://github.com/your/reproduction
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction
      description: A list of steps to reproduce the issue in the provided repository
      placeholder: 1)... 2)... 3)...
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Please include browser console and server logs around the time this bug occurred. Use `DEBUG='vite:*' <your start command here>` or `vite dev --debug`. No screenshots."
      render: shell
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --binaries --browsers --npmPackages "{svelte,svelte-hmr,@sveltejs/*,vite}"`
      render: shell
      placeholder: System, Binaries, Browsers
    validations:
      required: true
