name: "\U0001F680 Feature Request"
description: Request a new vite-plugin-svelte feature
labels: [enhancement, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request this feature! Please check if a similar request already exists before opening a new one.
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: Please provide a clear and concise description the problem this feature would solve. The more information you can provide here, the better.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the proposed solution
      description: Please provide a clear and concise description of what you would like to happen.
      placeholder: I would like to see...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: "Please provide a clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: true
  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to you?
      options:
        - nice to have
        - would make my life easier
        - i cannot use vite-plugin-svelte without it
    validations:
      required: true
